spring.data.mongodb.uri=mongodb://localhost:27017/ikazescholarship
spring.data.mongodb.database=ikazescholarship
server.port=8081

#Make them false in production
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true